<a href="https://colab.research.google.com/github/hyojunyee/kita_2404/blob/main/m3_%EB%B6%84%EC%84%9D%20%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC/pandas/pandas_1_%EB%8D%B0%EC%9D%B4%ED%84%B0%EA%B5%AC%EC%A1%B0_0528.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Contents
 - 데이터 구조 Series, DataFrame
 - 인덱스, 생성, 선택, 추가, 변경, 삭제, 전치
 - 파이썬 자료형과 양방향 변환

#### 판다스
Pandas는 파이썬에서 데이터 분석 및 조작을 위한 강력하고 유연한 오픈 소스 라이브러리. Series와 DataFrame 같은 고수준의 데이터 구조를 제공하여, 복잡한 데이터 조작을 직관적이고 효율적으로 수행할 수 있게 한다.

[Pandas의 주요 역할과 기능]

* DataFrame과 Series: 2차원 테이블과 1차원 배열 형태의 데이터 구조를 제공
* 데이터 처리: 결측값 처리, 데이터 정제, 필터링, 병합, 연결 및 변환 등을 위한 다양한 기능을 제공
* 데이터 분석: 기술통계, 그룹화, 시계열 분석 등 복잡한 분석 작업을 제공
* 입출력 기능: CSV, Excel, SQL, JSON 등 다양한 파일 형식의 데이터를 읽고 쓸 수 있는 기능을 제공
* 시각화 지원: 매트플롯립과 연동하여 데이터 시각화가 가능하도록 제공
* 라이브러리는 여러 종류의 class와 다양한 내장 함수로 구성. 시리즈와 데이터프레임은 대표적인 클래스 객체임
* 시리즈 인덱스는 데이터 값과 일대일 대응. 파이썬 딕셔너리와 비슷한 구조. pandas.Series(딕셔너리)

In [ ]:
# 시리즈 클래스 만들기
# pandas 불러오기 (pd)
import pandas as pd

# k:v 구조를 갖는 딕셔너리를 만들고 변수 dict_data에 저장
dict_data = {'a':1, 'b':2, 'c':3}

sr = pd.Series(dict_data)
print(sr)
print(type(sr))

a    1
b    2
c    3
dtype: int64


pandas.core.series.Series

In [ ]:
# 리스트를 시리즈로 변환

list_data = ['2019-07-02', 3.14, 'ABC', 100, True]
# sr - pd.Series(list_data, index = list('abcde'))
sr = pd.Series(list_data)
print(sr, type(sr))

0    2019-07-02
1          3.14
2           ABC
3           100
4          True
dtype: object <class 'pandas.core.series.Series'>


In [ ]:
# 인덱스 및 값
idx = sr.index
val = sr.values
print(idx)
# print(list(idx))
print(val)

RangeIndex(start=0, stop=5, step=1)
['2019-07-02' 3.14 'ABC' 100 True]


In [ ]:
# 튜플을 시리즈로 변환
tup_data = ('kevin', '2019-07-02', '남', True)

# sr = pd.Series(tup_data)
sr = pd.Series(tup_data, index = ['이름', '생년월일', '성별', '학생여부'])
idx = sr.index
val = sr.values
print(sr)
print(type(sr))

이름           kevin
생년월일    2019-07-02
성별               남
학생여부          True
dtype: object
<class 'pandas.core.series.Series'>


In [ ]:
sr = [1, 2, 3, 4, 5]
sr[1:3]

[2, 3]

In [ ]:
# 인덱싱
# import warnings
# warning.filterwarnings('ignore')
# 인덱스 명을 지정해도 숫자인덱스를 쓸 수 있음
print(sr[0])
print(sr['이름'])
print(sr[[1,2]])      # Series는 위치기반 멀티인덱싱을 사용하여 여러 요소를 선택 가능
# print(sr[1,2])      # 파이썬의 기본 인덱싱 방식으로 sr[1]과 같은 형태를 사용print(sr[1:2])

kevin
kevin
생년월일    2019-07-02
성별               남
dtype: object
생년월일    2019-07-02
dtype: object


In [ ]:
list('abcde')

['a', 'b', 'c', 'd', 'e']

In [ ]:
# 배열
import numpy as np

s1 = np.arange(11,21,2)
print(s1, type(s1))
print()
s2 = pd.Series(s1, index = list('abcde'))
print(s2, type(s2))

[11 13 15 17 19] <class 'numpy.ndarray'>

a    11
b    13
c    15
d    17
e    19
dtype: int64 <class 'pandas.core.series.Series'>


배열을 생성 후 시리즈로 변환하여 아래와 같이 출력하세요.

In [ ]:
data = np.arange(1000, 5000, 1000)
state = ['Califonia','Ohio','Oregon','Texas']
obj = pd.Series(data, index = state)
# dt = pd.Series(data)
# st = pd.Series(state, dt)
obj.name = 'population'
obj.index.name = 'state'
print(obj)
# print(st)

state
Califonia    1000
Ohio         2000
Oregon       3000
Texas        4000
Name: population, dtype: int64


#### None과 np.nan의 차이점
- None은 파이썬의 내장형 객체로 주로 객체데이터에서 사용
- np.nan은 부동 소수점으로 취급되며 주로 숫자형 데이터에서 사용
- 연산 시 np.nan은 NaN결과를 변환하는 반면 None은 TypeError를 발생시킨다.

In [ ]:
# nan(null)값 넣어주기
obj.Califonia = np.nan
print(obj)

state
Califonia       NaN
Ohio         2000.0
Oregon       3000.0
Texas        4000.0
Name: population, dtype: float64


In [ ]:
# null인 값 찾기
null_mask = obj.isnull()
print(null_mask)

state
Califonia     True
Ohio         False
Oregon       False
Texas        False
Name: population, dtype: bool


In [ ]:
# null이 아닌 값 찾기
not_null_mask = obj.notnull()
print(not_null_mask)

state
Califonia    False
Ohio          True
Oregon        True
Texas         True
Name: population, dtype: bool


In [ ]:
# null값 채워주기
filled_series = obj.fillna(0)
print(filled_series)

state
Califonia       0.0
Ohio         2000.0
Oregon       3000.0
Texas        4000.0
Name: population, dtype: float64


In [ ]:
obj.Califonia = np.nan
print(obj)

state
Califonia       NaN
Ohio         2000.0
Oregon       3000.0
Texas        4000.0
Name: population, dtype: float64


In [ ]:
# null값 개수의 합
obj.isnull().sum()

1

In [ ]:
# 삭제
dropped_series = obj.dropna()
print(dropped_series)

state
Ohio      2000.0
Oregon    3000.0
Texas     4000.0
Name: population, dtype: float64


In [ ]:
print(s2,type(s2))

a    11
b    13
c    15
d    17
e    19
dtype: int64 <class 'pandas.core.series.Series'>


In [ ]:
# Series -> List
list_from_series = s2.tolist()
print(list_from_series)

[11, 13, 15, 17, 19]


In [ ]:
# Series -> Dict
dict_from_series = s2.to_dict()
print(dict_from_series)

{'a': 11, 'b': 13, 'c': 15, 'd': 17, 'e': 19}


In [ ]:
# Series -> DataFrame
df_from_series = s2.to_frame(name = 'Value')

print(type(df_from_series))
df_from_series

<class 'pandas.core.frame.DataFrame'>


Value
a     11
b     13
c     15
d     17
e     19

Q. 아래 시리즈에서 null 값을 2개 입력 후 그 값을 0으로 대체 후 null값 여부를 확인한 후 출력하세요.

In [ ]:
import pandas as pd
import numpy as np

# 1. Series 생성
s = pd.Series([5, 15, 25, 35, 45], index=['x', 'y', 'z', 'w', 'v'])

# null값 두개 입력
s.w = np.nan
s.v = np.nan
print("null 갯수:", s.isnull().sum(), '\n')
# null값 채워주기
filled_series = s.fillna(0)
print("null 갯수:", s_filled.isna().sum(), '\n')
print(filled_series)

null 갯수: 2 

null 갯수: 0 

x     5.0
y    15.0
z    25.0
w     0.0
v     0.0
dtype: float64


In [ ]:
# 강사님 풀이
import pandas as pd
import numpy as np

# 1. Series 생성
s = pd.Series([5, 15, 25, 35, 45], index=['x', 'y', 'z', 'w', 'v'])

s['w'] = np.nan
s['v'] = np.nan

print("null 갯수:", s.isnull().sum(), '\n')

s_filled = s.fillna(0)
print("null 갯수:", s_filled.isna().sum(), '\n')
print(s_filled)

null 갯수: 2 

null 갯수: 0 

x     5.0
y    15.0
z    25.0
w     0.0
v     0.0
dtype: float64


Q. 주어진 리스트 [1, 2, 3, 4, 5]를 Pandas Series로 변환하고, 각 원소에 10을 더한 Series를 출력하세요.

In [ ]:
import pandas as pd

data_list = [1, 2, 3, 4, 5]

# Pandas Series로 변환
seri = pd.Series(data_list)

# 각 원소에 10을 더한 Series
seri_a10 = seri + 10

# 결과 출력
print("Original Series:")
print (seri)
print("\nSeries after adding 10 to each element:")
print(seri_a10)

Original Series:
0    1
1    2
2    3
3    4
4    5
dtype: int64

Series after adding 10 to each element:
0    11
1    12
2    13
3    14
4    15
dtype: int64


Q. Series [10, 20, 30, 40, 50]를 생성하고 인덱스를 ['a', 'b', 'c', 'd', 'e']로 설정하세요. 인덱스를 기준으로 Series를 정렬한 결과를 출력하세요.

In [ ]:
li = [10, 20, 30, 40, 50]
srli = pd.Series(li, index = list('abcde'))
print(srli)

a    10
b    20
c    30
d    40
e    50
dtype: int64


In [ ]:
# 강사님 풀이
# 주어진 데이터와 인덱스
data = [10, 20, 30, 40, 50]
idx = ['a', 'b', 'c', 'd', 'e']

# Pandas Series 생성
series = pd.Series(data, index = index)

# 인덱스를 기준으로 정렬
series_sorted = series.sort_index()

# 출력
print(series)
print(series_sorted)

a    10
b    20
c    30
d    40
e    50
dtype: int64
a    10
b    20
c    30
d    40
e    50
dtype: int64


Q. Series ['a':1, 'b':2, 'c':3, 'd':4, 'e':5]에서 인덱스 'b', 'd'에 해당하는 원소를 선택하여 출력하세요.

In [ ]:
import pandas as pd

# 주어진 데이터와 인덱스
data = [1, 2, 3, 4, 5]
index = ['a', 'b', 'c', 'd', 'e']

# Pandas Series 생성
sr1 = pd.Series(data, index)
print(sr1[['b']])
print(sr1[['d']])

b    2
dtype: int64
d    4
dtype: int64


In [ ]:
# 강사님 풀이
import pandas as pd

# 주어진 데이터와 인덱스
data = [1, 2, 3, 4, 5]
index = ['a', 'b', 'c', 'd', 'e']

# Pandas Series 생성
series = pd.Series(data, index = index)

# 인덱스 'b'와 'd'에 해당하는 원소 선택
selected_elements = series[['b','d']]

# 결과 출력
print(selected_elements)

b    2
d    4
dtype: int64


#### 데이터프레임
* 데이터프레임은 2차원 배열. R의 데이터프레임에서 유래.
* 데이터프레임의 열은 각각 시리즈 개체.
* 시리즈를 열벡터라고 하면 데이터프레임은 여러개의 열벡터들이 같은 행 인덱스를
  기준으로 줄지어 결합된 2차원 벡터 또는 행렬.
* 선형대수학에서 열 벡터(m x 1 행렬)는 m 원소들의 단일 열 행렬
* 행 벡터(1 x m 행렬)은 m원소들의 단일 행 행렬.
* 리스트, 딕셔너리, ndarray 등 다양한 데이터로부터 생성
* 반대로 리스트, 딕셔너리, ndarray 등으로 변환될 수 있음

In [ ]:
# seed(임의의숫자)를 하면 임의의 숫자를 넣으면 그 숫자에 랜덤값으로 고정된다.
np.random.seed(0)
np.random.randint(100,120,size=(3,3))

array([[114, 118, 100],
       [114, 103, 112],
       [110, 111, 104]])

In [ ]:
# 배열을 데이터프레임으로 변환
np.random.seed(0)
data = np.random.randint(100,120,size=(3,3))
print(data, type(data))

# index는 행인덱스로 들어가고 columns는 열 인덱스로 들어간다.
df = pd.DataFrame(data, index = ['d1','d2','d3'],
                  columns = ['pd','sales','inv'])
print(df,type(df))

[[112 115 100]
 [103 103 107]
 [109 119 118]] <class 'numpy.ndarray'>
     pd  sales  inv
d1  112    115  100
d2  103    103  107
d3  109    119  118 <class 'pandas.core.frame.DataFrame'>


In [ ]:
# 각 열은 하나의 시리즈 개체이다.
# 하나의 시리즈도 데이터 프레임이 될 수 있다.
print(df.pd, type(df.pd))

d1    112
d2    103
d3    109
Name: pd, dtype: int64 <class 'pandas.core.series.Series'>


In [ ]:
# 인덱스는 숫자로 자동생성됨.
df = pd.DataFrame(data, columns = ['pd','sales','inv'])
df

pd  sales  inv
0  112    115  100
1  103    103  107
2  109    119  118

#### Pandas의 iloc와 loc 메서드
DataFrame과 Series에서 데이터의 특정 위치나 라벨에 접근하기 위한 중요한 도구이며 두 메서드는 각각 고유한 용도를 가지고 있다.

- iloc (Integer Location)
  - 정수 인덱스 기반으로 데이터에 접근하는 메서드. 즉, DataFrame이나 Series의 특정 위치에 있는 데이터를 선택할 때 사용.
  - 슬라이싱 지원: Python 리스트와 유사하게 슬라이싱을 지원.
  - 끝점을 포함하지 않음: 슬라이싱 시 끝점은 포함하지 않는다.
- loc (Label Location)
  - 라벨 인덱스 기반으로 데이터에 접근하는 메서드. 즉, DataFrame이나 Series의 라벨 이름을 사용하여 데이터에 접근.
  - 슬라이싱 지원: 라벨을 사용하여 슬라이싱을 지원.
  - 끝점을 포함: 슬라이싱 시 끝점을 포함.

In [ ]:
# 데이터프레임 생성
data = {
    'A': [1, 2, 3, 4],
    'B': [5, 6, 7, 8],
    'C': [9, 10, 11, 12]
}
df = pd.DataFrame(data)
print(df,'\n')

# 첫번째 행, 두번째 열의 값 선택
print(df.iloc[0, 1])

# 첫번째 부터 두번째 행, 첫번째 부터 두번째 열 선택
print(df.iloc[0:2, 0:2])

   A  B   C
0  1  5   9
1  2  6  10
2  3  7  11
3  4  8  12 

5
   A  B
0  1  5
1  2  6


In [ ]:
# 데이터프레임 생성
data = {
    'A': [1, 2, 3, 4],
    'B': [5, 6, 7, 8],
    'C': [9, 10, 11, 12]
}
df = pd.DataFrame(data, index = ['a', 'b', 'c', 'd'])
print(df,'\n')

# 인덱스 'a'열 'B의 값 반환1
print(df.loc['a','B'])

# 첫번째 부터 두번째 행, 첫번째 부터 두번째 열 선택
print(type(df.loc['a','B']))

   A  B   C
a  1  5   9
b  2  6  10
c  3  7  11
d  4  8  12 

5
<class 'numpy.int64'>


In [ ]:
np.random.seed(0)
data = np.random.randint(100,120,size=(3,3))
print(data, type(data))
df = pd.DataFrame(data, index = ['d1','d2','d3'],
                  columns = ['pd','sales','inv'])
print(df,type(df))

[[112 115 100]
 [103 103 107]
 [109 119 118]] <class 'numpy.ndarray'>
     pd  sales  inv
d1  112    115  100
d2  103    103  107
d3  109    119  118 <class 'pandas.core.frame.DataFrame'>


In [ ]:
# pandas indexing : iloc 정수 인덱스, loc 이름 인덱스
print(df.iloc[1], "\n")
print(df.loc['d2'])

pd       103
sales    103
inv      107
Name: d2, dtype: int64 

pd       103
sales    103
inv      107
Name: d2, dtype: int64


In [ ]:
print(df.iloc[1,:],'\n')
print(df.loc['d2',:])

pd       103
sales    103
inv      107
Name: d2, dtype: int64 

pd       103
sales    103
inv      107
Name: d2, dtype: int64


In [ ]:
# Q. 107을 출력해봐라
print(df.iloc[1,2],'\n')
print(df.loc['d2','inv'])

107 

107


In [ ]:
# 해당되는 인덱스에다 값을 집어넣는다!
df.loc['d3'] = 0
print(df)

     pd  sales  inv
d1  112    115  100
d2  103    103  107
d3    0      0    0
d4    0      0    0


In [ ]:
# 새로운 'd4'를 생성하고 값을 넣기
df.loc['d4'] = 0
print(df)

     pd  sales  inv
d1  112    115  100
d2  103    103  107
d3    0      0    0
d4    0      0    0


In [ ]:
# 컬럼쪽으로 추가하기 ':'(횡쪽은 전부다 값을 넣기)
df.loc[:,'profit'] = 10
print(df)

     pd  sales  inv  profit
d1  112    115  100      10
d2  103    103  107      10
d3    0      0    0      10
d4    0      0    0      10


In [ ]:
import random
print(random.random(),'\n') # 0.0 <= x < 1.0 사이
print(random.randint(1,10),'\n') # 1에서 10사이의 정수중에서 난수 값 리턴
print(random.uniform(10,20), '\n') # min max 사이 float 리턴
print(random.randrange(10), '\n') # 지정 범위 int 리턴
print(random.choice([1,2,3,4,5]),'\n') # 리스트 내부에 있는 요소를 랜덤하게 선택
li = [1,2,3,4,5]
print(random.sample(li,3),'\n') # 리스트 요소를 중복이 안되게 리턴
random.shuffle(li) # 리스트 요소를 다시 섞어서 리턴
print(li)

0.6481880807675952 

4 

19.35044727160023 

9 

4 

[3, 1, 2] 

[2, 3, 1, 5, 4]


[numpy random 함수]

- np.random.seed : seed를 통한 난수 생성
- np.random.randint : 정수 난수 1개 생성
- np.random.rand : 0부터 1사이의 균일분포에서 난수 매트릭스 배열 생성
- np.random.randn : 가우시안 표준 정규분포에서 난수 매트릭스 배열 생성
- np.random.shuffle : 기존의 데이터의 순서 바꾸기
- np.random.choice : 기존 데이터에서 sampling

In [ ]:
import numpy as np
print(np.random.randint(6), '\n') # 0 ~ 5까지 정수인 난수 1개
print(np.random.randint(1,20),'\n') # 1 ~ 19까지 정수인 난수 1개
print(np.random.randint(10, size=10), '\n') # 0 ~ 9까지 정수인 난수 10개
print(np.random.randint(10,20, size=10),'\n') # 10 ~ 19까지 정수인 난수 10개
print(np.random.randint(10,20, size=(3,5))) # 10 ~ 19까지 정수인 난수로 3행 5열 배열 생성

4 

7 

[8 8 1 6 7 7 8 1 5 9] 

[18 19 14 13 10 13 15 10 12 13] 

[[18 11 13 13 13]
 [17 10 11 19 19]
 [10 14 17 13 12]]


In [ ]:
# id, gender, age, region
import numpy as np
import pandas as pd
id = np.arange(1,1001)
i1 = pd.Series(id)
gender = np.random.randint(1,3,size=1000)
g1 = pd.Series(gender)
age = np.random.randint(1,101,size=1000)
a1 = pd.Series(age)
region = np.random.randint(1,11,size=1000)
r1 = pd.Series(region)

# axis -> 축을 의미
df = pd.concat([i1,g1,a1,r1],axis=1)
df.rename(columns={0:'id',1:'gender',2:'age',3:'region',},inplace=True)
df.head()

id  gender  age  region
0   1       1   87       1
1   2       2   14       3
2   3       2   89       5
3   4       1    3       8
4   5       2    3      10

In [ ]:
# 삭제 후 원본에 반영
# 0번 인덱스의 값들이 없어짐
df.drop([0], axis=0, inplace=True)
df.head()

id  gender  age  region
1   2       1    8       4
2   3       2   83       7
3   4       1   50       9
4   5       1   68       6
5   6       1    8       5

- at은 라벨 기반 인덱싱을 사용. 단일 값을 접근할 때 loc 접근자 보다 빠름
- 여러 값을 동시에 접근하려면 loc 접근자를 사용

In [ ]:
# df.loc[5,'id']
df.at[5,'id']

6

In [ ]:
# 단일값을 지정해서 지우는데 사용한 케이스
df1 = df.drop(df.at[5,'id'])
df1.head(7)

id  gender  age  region
0   1       1   87       1
1   2       2   14       3
2   3       2   89       5
3   4       1    3       8
4   5       2    3      10
5   6       1   29       3
7   8       2   79       5

In [ ]:
# 기존의 데이터 프레임을 복사해서 쓸 수 있음
df1 = df.copy()
df1.head()

id  gender  age  region
0   1       1   87       1
1   2       2   14       3
2   3       2   89       5
3   4       1    3       8
4   5       2    3      10

In [ ]:
np.random.seed(0)
a = np.random.randint(1,5,size=(10,5))
print(a, type(a))

[[1 4 2 1 4]
 [4 4 4 2 4]
 [2 3 1 4 3]
 [1 1 1 3 2]
 [3 4 4 3 1]
 [2 2 2 2 1]
 [2 1 4 1 4]
 [2 3 4 4 1]
 [3 4 1 2 4]
 [2 4 4 3 4]] <class 'numpy.ndarray'>


In [ ]:
# 2차원 리스트를 데이터 프레임으로 변환
list1 = a.tolist()
# print(list1, type(list))

df1 = pd.DataFrame(list1, columns=['c1','c2','c3','c4','c5'])
print(df1.head())

   c1  c2  c3  c4  c5
0   1   4   2   1   4
1   4   4   4   2   4
2   2   3   1   4   3
3   1   1   1   3   2
4   3   4   4   3   1


In [ ]:
# 데이터프레임을 배열, 리스트, 딕셔너리로 변환
ar = df1.values
print(ar,type(ar))
print()
li = ar.tolist()
print(li,type(li))
print()
dict = df1.to_dict('list')
print(dict,type(dict))

[[1 4 2 1 4]
 [4 4 4 2 4]
 [2 3 1 4 3]
 [1 1 1 3 2]
 [3 4 4 3 1]
 [2 2 2 2 1]
 [2 1 4 1 4]
 [2 3 4 4 1]
 [3 4 1 2 4]
 [2 4 4 3 4]] <class 'numpy.ndarray'>

[[1, 4, 2, 1, 4], [4, 4, 4, 2, 4], [2, 3, 1, 4, 3], [1, 1, 1, 3, 2], [3, 4, 4, 3, 1], [2, 2, 2, 2, 1], [2, 1, 4, 1, 4], [2, 3, 4, 4, 1], [3, 4, 1, 2, 4], [2, 4, 4, 3, 4]] <class 'list'>

{'c1': [1, 4, 2, 1, 3, 2, 2, 2, 3, 2], 'c2': [4, 4, 3, 1, 4, 2, 1, 3, 4, 4], 'c3': [2, 4, 1, 1, 4, 2, 4, 4, 1, 4], 'c4': [1, 2, 4, 3, 3, 2, 1, 4, 2, 3], 'c5': [4, 4, 3, 2, 1, 1, 4, 1, 4, 4]} <class 'dict'>


In [8]:
# file 생성
import pandas as pd
file_data = pd.DataFrame({
    'col1':[1,2,3,4,5,6],
    'col2':['A','A','B','B','C','C']
})
print(file_data)

   col1 col2
0     1    A
1     2    A
2     3    B
3     4    B
4     5    C
5     6    C


In [9]:
# 파일데이터 만든 것을 csv로 저장
# index = None, False를 넣으면 인덱스가 제외되지 않음.
file_data.to_csv('file_data.csv')
# file_data.to_csv('file_data.csv', index=None)
print(file_data)

   col1 col2
0     1    A
1     2    A
2     3    B
3     4    B
4     5    C
5     6    C


In [4]:
!ls

file_data.csv  sample_data


In [5]:
# 저장한 csv 파일을 불러오기(read_cvs)
file_data = pd.read_csv('file_data.csv')
print(file_data,type(file_data))

   col1 col2
0     1    A
1     2    A
2     3    B
3     4    B
4     5    C
5     6    C <class 'pandas.core.frame.DataFrame'>


In [11]:
import numpy as np
import pandas as pd

df_1 = pd.DataFrame({
    'col1':np.array([1,2,3]),
    'col2':np.array(['A','B','C'])
})
df_2 = pd.DataFrame({
    'col1':np.array([4,5,6]),
    'col2':np.array(['D','E','F'])
})
print(df_1)
print()
print(df_2)

   col1 col2
0     1    A
1     2    B
2     3    C

   col1 col2
0     4    D
1     5    E
2     6    F


In [12]:
# Q. df1_1과 df_2를 행방향과 열방향으로 병합하여 출력하세요
df_3 = pd.concat([df_1,df_2],axis=1)
df_4 = pd.concat([df_1,df_2])
print(df_3)
print()
print(df_4)

   col1 col2  col1 col2
0     1    A     4    D
1     2    B     5    E
2     3    C     6    F

   col1 col2
0     1    A
1     2    B
2     3    C
0     4    D
1     5    E
2     6    F


In [14]:
# 두번째 컬럼만 찾기
df_4.iloc[:,1]

0    A
1    B
2    C
0    D
1    E
2    F
Name: col2, dtype: object

In [13]:
# 'col2'만 찾기(Series가 됨)
df_4['col2']

0    A
1    B
2    C
0    D
1    E
2    F
Name: col2, dtype: object

In [15]:
# 첫번째 행만 찾기
df_4.iloc[1]

col1    2
col2    B
Name: 1, dtype: object

In [16]:
# 데이터프레임 생성(8행 5열)
import numpy as np
import pandas as pd

np.random.seed(3)
data = np.random.randint(50,100,size=(8,5))

df = pd.DataFrame(data, columns=list('abcde'))
df

a   b   c   d   e
0  92  74  53  58  50
1  71  69  60  93  91
2  60  71  88  82  70
3  94  79  89  64  76
4  67  76  72  52  52
5  51  76  55  90  96
6  83  79  92  74  57
7  93  83  65  98  87

In [20]:
# 열이름과 행이름 변경
# 딕셔너리 타입으로 변경해 줄 수 있다.
columns = {'a':'국어','b':'영어','c':'수학','d':'과학','e':'음악'}
index = {0:'a',1:'b',2:'c',3:'d',4:'e',5:'f',6:'g',7:'h'}
df.rename(columns=columns,index=index,inplace=True)
df

국어  영어  수학  과학  음악
a  92  74  53  58  50
b  71  69  60  93  91
c  60  71  88  82  70
d  94  79  89  64  76
e  67  76  72  52  52
f  51  76  55  90  96
g  83  79  92  74  57
h  93  83  65  98  87

In [23]:
# 데이터프레임 생성
import numpy as np
import pandas as pd
np.random.seed(0)

data = np.random.randint(80,100,size=(5,5))
df = pd.DataFrame(data, columns=list('abcde'))
df

a   b   c   d   e
0  92  95  80  83  83
1  87  89  99  98  84
2  86  92  81  86  87
3  94  97  85  93  88
4  89  99  96  99  85

In [24]:
df1 = df.copy()
df1

a   b   c   d   e
0  92  95  80  83  83
1  87  89  99  98  84
2  86  92  81  86  87
3  94  97  85  93  88
4  89  99  96  99  85

In [25]:
# '가', '나', '다', '라', '마'라는 값을 가진 'index'라는 새로운 열을 df1 데이터프레임에 추가
df1['index'] = list('가나다라마')
df1

a   b   c   d   e index
0  92  95  80  83  83     가
1  87  89  99  98  84     나
2  86  92  81  86  87     다
3  94  97  85  93  88     라
4  89  99  96  99  85     마

In [50]:
# 'index' 열을 인덱스로 설정하여 df2라는 새로운 데이터프레임을 만듭니다. 기존 인덱스는 'index' 열로 대체됨
df2 = df1.set_index('index')
df2

a   b   c   d   e
index                    
가      92  95  80  83  83
나      87  89  99  98  84
다      86  92  81  86  87
라      94  97  85  93  88
마      89  99  96  99  85

In [51]:
# 'e' 열을 삭제하여 df21 데이터프레임을 만듭니다. axis=1은 열을 삭제
python
df21 = df2.drop('e',axis=1)
df21

a   b   c   d
index                
가      92  95  80  83
나      87  89  99  98
다      86  92  81  86
라      94  97  85  93
마      89  99  96  99

In [53]:
# 인덱스를 리셋하여 기존 인덱스를 새로운 열로 추가하고, 인덱스를 기본 정수 인덱스로 변경합니다. 결과는 df3 데이터프레임에 저장
df3 = df2.reset_index()
df3

index   a   b   c   d   e
0     가  92  95  80  83  83
1     나  87  89  99  98  84
2     다  86  92  81  86  87
3     라  94  97  85  93  88
4     마  89  99  96  99  85

In [54]:
# 이터프레임의 인덱스를 리셋하여 기본 정수 인덱스로 변경하고, 기존 인덱스를 열로 추가합니다. 결과는 df22 데이터프레임에 저장
df22 = df21.reset_index()
df22

index   a   b   c   d
0     가  92  95  80  83
1     나  87  89  99  98
2     다  86  92  81  86
3     라  94  97  85  93
4     마  89  99  96  99

In [56]:
# df22 데이터프레임의 인덱스 이름을 제거하여 인덱스에 이름이 없도록 설정합니다.
df22.index.name = None
df22

index   a   b   c   d
0     가  92  95  80  83
1     나  87  89  99  98
2     다  86  92  81  86
3     라  94  97  85  93
4     마  89  99  96  99

In [57]:
# 딕셔서리를 정의
dict_data = {'a':[1,2,3,4,5], 'b':[4,5,6,7,8], 'c':[7,8,9,10,11], 'd':[10,11,12,13,14], 'e':[13,14,15,16,17]}

# 딕셔서리를 데이터프레임으로 변환. 인덱스를 [r0, r1, r2]로 지정
df = pd.DataFrame(dict_data, index=['r0','r1','r2','r3','r4'])
df

a  b   c   d   e
r0  1  4   7  10  13
r1  2  5   8  11  14
r2  3  6   9  12  15
r3  4  7  10  13  16
r4  5  8  11  14  17

In [58]:
# Q. df에 r5,r6의 두개행을 추가하고 값은 0을 적용하여 출력하세요
df.loc['r5'] = 0
df.loc['r6'] = 0
df

a  b   c   d   e
r0  1  4   7  10  13
r1  2  5   8  11  14
r2  3  6   9  12  15
r3  4  7  10  13  16
r4  5  8  11  14  17
r5  0  0   0   0   0
r6  0  0   0   0   0

In [59]:
# reindex를 사용하여 추가 할 수 도 있음. 여기서는 'r7','r8'
new_index = ['r0','r1','r2','r3','r4','r5','r6','r7','r8']
df5 = df.reindex(new_index,fill_value=0)
df5

a  b   c   d   e
r0  1  4   7  10  13
r1  2  5   8  11  14
r2  3  6   9  12  15
r3  4  7  10  13  16
r4  5  8  11  14  17
r5  0  0   0   0   0
r6  0  0   0   0   0
r7  0  0   0   0   0
r8  0  0   0   0   0

In [60]:
# 원하는것만 줄여서 출력도 가능하다.
new_index = ['r0','r1','r2','r3','r4']
df1 = df.reindex(new_index,fill_value=0)
df1

a  b   c   d   e
r0  1  4   7  10  13
r1  2  5   8  11  14
r2  3  6   9  12  15
r3  4  7  10  13  16
r4  5  8  11  14  17

In [61]:
# 드랍을 써서 줄여서 출력하는법.
df1 = df5.drop(df5.index[5:9])
df1

a  b   c   d   e
r0  1  4   7  10  13
r1  2  5   8  11  14
r2  3  6   9  12  15
r3  4  7  10  13  16
r4  5  8  11  14  17

In [64]:
df1 = df5.drop(['r5','r6','r7','r8'], axis=0)
df1

a  b   c   d   e
r0  1  4   7  10  13
r1  2  5   8  11  14
r2  3  6   9  12  15
r3  4  7  10  13  16
r4  5  8  11  14  17

In [65]:
# 인덱스기준 내림차순 정렬
df1_s = df1.sort_index(ascending=False)
df1_s

a  b   c   d   e
r4  5  8  11  14  17
r3  4  7  10  13  16
r2  3  6   9  12  15
r1  2  5   8  11  14
r0  1  4   7  10  13

In [67]:
# 특정 벨류 기준으로 내림차순 정렬
df1_c = df1.sort_values(by='c',ascending=False)
df1_c

a  b   c   d   e
r4  5  8  11  14  17
r3  4  7  10  13  16
r2  3  6   9  12  15
r1  2  5   8  11  14
r0  1  4   7  10  13

In [69]:
# 전치(열과 행 인덱스를 바꾸는것)
# 정방행렬(행과 열의 숫자가 같은 것)의 경우에만 가능.
df1_t = df1.transpose()
# df1_t = df1.T()
df1_t

r0  r1  r2  r3  r4
a   1   2   3   4   5
b   4   5   6   7   8
c   7   8   9  10  11
d  10  11  12  13  14
e  13  14  15  16  17

In [72]:
# 연습. 전치한것을 다시 전치해봐라
df1_tt = df1_t.transpose()
df1_tt

a  b   c   d   e
r0  1  4   7  10  13
r1  2  5   8  11  14
r2  3  6   9  12  15
r3  4  7  10  13  16
r4  5  8  11  14  17