<a href="https://colab.research.google.com/github/hyojunyee/kita_2404/blob/main/m3_%EB%B6%84%EC%84%9D%20%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC/pandas/pandas_2_%EC%97%B0%EC%82%B0_0528.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Contetnts
- 기초 연산
- 그룹 연산 : 집계, 변환, 필터링, 그룹매핑
- 함수 매핑 : map, apply, applymap
- Pivot

In [1]:
import pandas as pd
st1 = pd.Series({'국어':100,'영어':80,'수학':90})
st2 = pd.Series({'수학':80,'국어':90,'영어':80})

print(st1,'\n')
print(st2)

국어    100
영어     80
수학     90
dtype: int64 

수학    80
국어    90
영어    80
dtype: int64


In [10]:
# 두 데이터 프레임의 덧셈
pd.DataFrame(st1 + st2)

0
국어  190
수학  170
영어  160

In [11]:
add = st1 + st2
sub = st1 - st2
mul = st1 * st2
div = round((st1 / st2),2)

df = pd.concat([add,sub,mul,div],axis=1)
df

0   1     2     3
국어  190  10  9000  1.11
수학  170  10  7200  1.12
영어  160   0  6400  1.00

In [14]:
df = pd.concat([add,sub,mul,div],axis=1)
df.columns = ['덧셈','뺄셈','곱셈','나눗셈']
# df.index.name = '과목'
df

덧셈  뺄셈    곱셈   나눗셈
국어  190  10  9000  1.11
수학  170  10  7200  1.12
영어  160   0  6400  1.00

In [15]:
print(add,type(add))

국어    190
수학    170
영어    160
dtype: int64 <class 'pandas.core.series.Series'>


In [19]:
# 데이터 프레임에 리스트로 주면 행으로 들어감.
# 여기서는 인덱스에 넣어줘야된다.
result = pd.DataFrame([add,sub,mul,div],index = ['덧셈','뺄셈','곱셈','나눗셈'])

result

국어       수학      영어
덧셈    190.00   170.00   160.0
뺄셈     10.00    10.00     0.0
곱셈   9000.00  7200.00  6400.0
나눗셈     1.11     1.12     1.0

In [32]:
import numpy as np
import pandas as pd

st1 = pd.Series({'국어':np.nan,'영어':80,'수학':90})
st2 = pd.Series({'수학':80,'국어':90})

add = st1 + st2
sub = st1 - st2
mul = st1 * st2
div = round((st1 / st2),2)

result = pd.DataFrame([add,sub,mul,div],
                      index = ['덧셈','뺄셈','곱셈','나눗셈'])
result

국어       수학  영어
덧셈  NaN   170.00 NaN
뺄셈  NaN    10.00 NaN
곱셈  NaN  7200.00 NaN
나눗셈 NaN     1.12 NaN

In [36]:
st1 = pd.Series({'국어':np.nan,'영어':80,'수학':90})
st2 = pd.Series({'수학':80,'국어':90})

ad = st1.add(st2, fill_value=0)
su = st1.sub(st2, fill_value=0)
mu = st1.mul(st2, fill_value=0)
di = st1.div(st2, fill_value=0)

df = pd.DataFrame([ad,su,mu,di],
                      index = ['덧셈','뺄셈','곱셈','나눗셈'])
df

국어        수학    영어
덧셈   90.0   170.000  80.0
뺄셈  -90.0    10.000  80.0
곱셈    0.0  7200.000   0.0
나눗셈   0.0     1.125   inf

In [42]:
# reshape는 차원의 개념(행/열)
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)), columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)), columns=list('abcde'))
print(df1)
print(df2)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0
      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0


In [44]:
df2.loc[1,'b'] = np.nan
print(df1)
print(df2)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0
      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0


In [43]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [49]:
# r을 붙여 계산 인자를 뒤집어 계산
print(df1)
print(df1.radd(1))
print(df1.rsub(2))
print(df1.rmul(3))
print(round(df1.rdiv(4),2))

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0
     a     b     c     d
0  1.0   2.0   3.0   4.0
1  5.0   6.0   7.0   8.0
2  9.0  10.0  11.0  12.0
     a    b    c    d
0  2.0  1.0  0.0 -1.0
1 -2.0 -3.0 -4.0 -5.0
2 -6.0 -7.0 -8.0 -9.0
      a     b     c     d
0   0.0   3.0   6.0   9.0
1  12.0  15.0  18.0  21.0
2  24.0  27.0  30.0  33.0
     a     b     c     d
0  inf  4.00  2.00  1.33
1  1.0  0.80  0.67  0.57
2  0.5  0.44  0.40  0.36


In [61]:
arr = np.arange(12.).reshape((3,4))
print(arr)
print(arr[0])

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[0. 1. 2. 3.]


In [60]:
# broadcasting
# 각 행마다 지정 값(arr[0])의 값을 빼준다.
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [63]:
# DataFrame과 Series간 연산
frame = pd.DataFrame(np.arange(12.).reshape(4,3),columns=list('bde'),
                    index = ['Utah','Ohio','Texas','Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [64]:
# DataFrame의 값이랑 Series 간에도 연산됨.
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [65]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [66]:
# 대괄호가 두개생김(2차원데이터)
a = np.arange(6).reshape(1,6)
a

array([[0, 1, 2, 3, 4, 5]])

In [68]:
# 튜플(x,)로 사용하여 1차원데이터로 만들기.
a = np.arange(6).reshape(6,)
a

array([0, 1, 2, 3, 4, 5])

#### 그룹 연산
* 복잡한 데이터를 어떤 기준에 따라 여러 그룹으로 나누어서 관찰할 수 있으며 이런 방식으로 분할 처리하는 것을 그룹 연산이라 함
* 그룹 연산은 데이터를 집계, 변환, 필터링하는데 효율적이며 판다스 groupby() 메소드를 사용함
* 그룹 객체 만들기(분할)
* 그룹 연산 메소드(적용-결합)

In [73]:
import seaborn as sns

# titanic 데이터셋에서 age, sex 등 5개 열을 선택하여 데이터셋 만들기
titanic = sns.load_dataset('titanic')
df = titanic.loc[:,['age','sex','class','fare','survived']]
# df = titanic[['age','sex','class','fare','survived']]
df

age     sex   class     fare  survived
0    22.0    male   Third   7.2500         0
1    38.0  female   First  71.2833         1
2    26.0  female   Third   7.9250         1
3    35.0  female   First  53.1000         1
4    35.0    male   Third   8.0500         0
..    ...     ...     ...      ...       ...
886  27.0    male  Second  13.0000         0
887  19.0  female   First  30.0000         1
888   NaN  female   Third  23.4500         0
889  26.0    male   First  30.0000         1
890  32.0    male   Third   7.7500         0

[891 rows x 5 columns]

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype   
---  ------    --------------  -----   
 0   age       714 non-null    float64 
 1   sex       891 non-null    object  
 2   class     891 non-null    category
 3   fare      891 non-null    float64 
 4   survived  891 non-null    int64   
dtypes: category(1), float64(2), int64(1), object(1)
memory usage: 29.0+ KB


In [75]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB
