<a href="https://colab.research.google.com/github/hyojunyee/kita_2404/blob/main/m3_%EB%B6%84%EC%84%9D%20%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC/Task/Task_0610.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

Task1_0610. 주어진 두 배열 arr1과 arr2에서, arr2의 요소가 10보다 큰 위치의 arr1 요소들을 선택하세요.

In [4]:
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([5, 15, 25, 10, 35])
mask = arr2 > 10
# print(mask)
numarr = arr1[mask]

print(numarr)

[False  True  True False  True]
[20 30 50]


Task2_0610. 주어진 배열에서 짝수 인덱스에 있는 요소들을 선택하세요.

In [10]:
arr = np.array([5, 10, 15, 20, 25, 30, 35, 40])
mask = arr % 2 == 1
numarr = arr[mask]
# print(mask)
print(numarr)

[ 5 15 25 35]


In [9]:
arr = np.array([5, 10, 15, 20, 25, 30, 35, 40])
numarr = arr[::2]
print(numarr)

[ 5 15 25 35]


Task3_0610. 주어진 배열에서 20보다 작은 요소들의 값을 0으로 변경하세요.

In [8]:
arr = np.array([10, 25, 30, 15, 40, 5])

mask = arr < 20
numarr = arr[mask]
arr[mask] = 0
# print(mask)
# print(numarr)
print(arr)

[ True False False  True False  True]
[10 15  5]
[ 0 25 30  0 40  0]


In [11]:
arr = np.array([10, 25, 30, 15, 40, 5])
arr[arr < 20] = 0
print(arr)

[ 0 25 30  0 40  0]
