<a href="https://colab.research.google.com/github/hyojunyee/kita_2404/blob/main/m3_%EB%B6%84%EC%84%9D%20%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC/Task/Task_0611.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

Task1_0611. 주어진 대각 행렬의 역행렬을 구하고, 역행렬이 맞는지 확인하세요.

In [4]:
# 대각행렬 정의
D = np.diag([1, 2, 3])
# 대각행렬의 역행렬
D_inv = np.linalg.inv(D)
print(D,'\n',D_inv)
#원래 행렬과 대각행렬의 곱
result = np.allclose(D, D_inv)
print(D @ D_inv)
print(result)

[[1 0 0]
 [0 2 0]
 [0 0 3]] 
 [[1.         0.         0.        ]
 [0.         0.5        0.        ]
 [0.         0.         0.33333333]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
False


Task2_0611. 임의의 상삼각 행렬을 생성하고, 그 행렬로 부터 하삼각 행렬을 구하여 출력하세요.

In [12]:
# 상삼각행렬 정의
a = np.triu(np.round(np.random.rand(3, 3)))

# 상삼각행렬의 전치
a.T

print("Upper Triangular Matrix U = \n", a)
print("Lower Triangular Matrix L = \n", a.T)

Upper Triangular Matrix U = 
 [[0. 1. 1.]
 [0. 0. 1.]
 [0. 0. 0.]]
Lower Triangular Matrix L = 
 [[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]]


In [ ]:
a = np.triu(np.random.rand(3, 3))
np.round(a.T,2)

array([[0.11, 0.  , 0.  ],
       [0.42, 0.42, 0.  ],
       [0.39, 0.04, 0.02]])

In [ ]:
import random as rd

a = np.triu(np.random.randint(10, size=(3, 3)))
a.T

array([[9, 0, 0],
       [3, 9, 0],
       [1, 7, 8]])

Task3_0611. 주어진 행렬의 역행렬을 구하고, 역행렬이 맞는지 확인하세요.

In [21]:
A = np.array([[4, 7], [2, 6]])
A_inv = np.linalg.inv(A)
result = np.dot(A, A_inv)
# 단위행렬
I = np.eye(2)
print("Araay = \n",A)
print("Inverse of Array = \n",A_inv)
print("A * A_inv =\n", result)
np.allclose(result, I)

Araay = 
 [[4 7]
 [2 6]]
Inverse of Array = 
 [[ 0.6 -0.7]
 [-0.2  0.4]]
A * A_inv =
 [[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


True

Task4_0611. 주어진 데이터 포인트와 모델 파라미터를 사용하여 선형 회귀 모델의 예측값을 계산하세요.

- 1단계 : 주어진 입력 데이터 포인트 X와 모델 파라미터 θ를 정의.
- 2단계 : 행렬 곱을 사용하여 예측값 y를 계산.

In [25]:
X = np.array([1, 2, 3])
theta = np.array([0.2, 0.3, 0.4])
y = np.dot(X, theta)
print("input Data Point X =\n",X)
print("Model Parameters θ =\n",theta)
print("Predicted Value y =\n",y)

input Data Point X =
 [1 2 3]
Model Parameters θ =
 [0.2 0.3 0.4]
Predicted Value y =
 2.0


In [22]:
# 입력 데이터 포인트(1,ㅌ1,ㅌ2)
X = np.array([1, 2, 3])

# 모델 파라미터(bias, w1, w2)
theta = np.array([0.5, 1.5, -2])

# 선형 회기 모델의 예측값 계산
y = np.dot(X, theta)

print("Input Data Point X =\n",X)
print("Model Parameters θ =\n",theta)
print("Predicted Value y =\n",y)

Input Data Point X =
 [1 2 3]
Model Parameters θ =
 [ 0.5  1.5 -2. ]
Predicted Value y =
 -2.5


Task5_0611. 주어진 입력 벡터와 가중치 행렬을 사용하여 신경망의 단일 계층 출력을 계산하세요.

- 1단계: 입력 벡터 X와 가중치 행렬 W를 정의.
- 2단계: 행렬 곱을 사용하여 계층의 출력을 계산.

In [27]:
# W는 가중치 행렬, X는 입력벡터이고 일반적인 표기방식은 WX

# 입력벡터
X = np.array([0.5, 1.0, -1.5])

# 가중치 행렬 W
W = np.array([
    [0.1, 0.2, 0.3],
    [-0.4, -0.5, -0.6],
    [-0.1, -0.2, -0.3]
])

# 신경망의 단일 계층 출력
output = np.dot(W, X)

print("Input Vector X =\n",X)
print("Weight Matrix W =\n",W)
print("Layer Output =\n",output)

Input Vector X =
 [ 0.5  1.  -1.5]
Weight Matrix W =
 [[ 0.1  0.2  0.3]
 [-0.4 -0.5 -0.6]
 [-0.1 -0.2 -0.3]]
Layer Output =
 [-0.2 -0.1  0. ]


In [31]:
# W는 가중치 행렬, X는 입력벡터이고 일반적인 표기방식은 WX

# 입력벡터
X = np.array([0.5, 1.0, -1.5])

# 가중치 행렬 W
W = np.array([
    [0.1, -0.3, 0.5],
    [-0.4, 0.1, -0.2],
    [-0.5, 0.4, 0.3]
])

# 신경망의 단일 계층 출력
output = np.dot(W, X)
# output = np.dot(X, W)

print("Input Vector X =\n",X)
print("Weight Matrix W =\n",W)
print("Layer Output =\n",output)

Input Vector X =
 [ 0.5  1.  -1.5]
Weight Matrix W =
 [[ 0.1 -0.3  0.5]
 [-0.4  0.1 -0.2]
 [-0.5  0.4  0.3]]
Layer Output =
 [ 0.4  -0.65 -0.4 ]


Task6_0611. 주어진 입력 벡터에 대해 신경망의 활성화 함수(ReLU, 시그모이드)를 적용하여 출력을 계산하세요.

- 1단계: 입력 벡터 X를 정의.
- 2단계: 가중치 행렬 W와 편향 벡터 b를 정의.
- 3단계: 활성화 함수(ReLU, 시그모이드)를 적용하여 출력을 계산<br>
활성화 함수 적용<br>
output_relu = relu(Z)<br>
output_sigmoid = sigmoid(Z)

In [32]:
# 활성화 함수 정의
def relu(x):
    return np.maximum(0, x)
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# 입력 벡터 정의
X = np.array([1, -2, 3])

# 가중치 행렬과 편향 벡터 정의
W = np.array([
    [0.2, 0.5, 0.3],
    [0.4, 0.1, -0.2],
    [-0.3, -0.2, 0.3]
])
b = np.array([0.1, -0.2, 0.3])

# 활성화 함수 적용
Z = np.dot(X, W) + b
output_relu = relu(Z)
output_sigmoid = sigmoid(Z)

print("Input Vector X =\n",X)
print("Weight Matrix W =\n",W)
print("Bias Vector b =\n",b)
print("Z =\n",Z)
print("ReLU Output =\n",output_relu)
print("Sigmoid Output =\n",output_sigmoid)

Input Vector X =
 [ 1 -2  3]
Weight Matrix W =
 [[ 0.2  0.5  0.3]
 [ 0.4  0.1 -0.2]
 [-0.3 -0.2  0.3]]
Bias Vector b =
 [ 0.1 -0.2  0.3]
Z =
 [-1.4 -0.5  1.9]
ReLU Output =
 [0.  0.  1.9]
Sigmoid Output =
 [0.19781611 0.37754067 0.86989153]


In [33]:
import tensorflow as tf
from tensorflow.keras.activations import relu, sigmoid
X = np.array([1, -2, 3])
W = np.array([
    [0.2, 0.5, 0.3],
    [0.4, 0.1, -0.2],
    [-0.3, -0.2, 0.3]
])
b = np.array([0.1, 0.2, 0.3])

Z = np.dot(X, W) + b

output_relu = relu(Z)
output_sigmoid = sigmoid(Z)

print("Input Vector X =\n",X)
print("Weight Matrix W =\n",W)
print("Bias Vector b =\n",b)
print("Z =\n",Z)
print("ReLU Output =\n",output_relu)
print("Sigmoid Output =\n",output_sigmoid)

Input Vector X =
 [ 1 -2  3]
Weight Matrix W =
 [[ 0.2  0.5  0.3]
 [ 0.4  0.1 -0.2]
 [-0.3 -0.2  0.3]]
Bias Vector b =
 [0.1 0.2 0.3]
Z =
 [-1.4 -0.1  1.9]
ReLU Output =
 tf.Tensor([0.  0.  1.9], shape=(3,), dtype=float64)
Sigmoid Output =
 tf.Tensor([0.19781611 0.47502081 0.86989153], shape=(3,), dtype=float64)


Task7_0611. 주어진 선형 방정식을 행렬 형태로 나타내고, 역행렬을 사용하여
x와 y를 구하세요.

$\begin{cases}
3x + 4y = 10 \\
2x + y = 5
\end{cases}$

단계:
1. 계수 행렬 A와 결과 벡터 b를 정의.
2. 행렬 A의 역행렬을 구한다.
3. 역행렬을 사용하여 변수 x를 구한다.

[풀이]
주어진 선형방정식을 행렬 형태로 나타내면 다음과 같다: \\
$A\mathbf{x} = \mathbf{b}$ \\
여기서 \\
$A = \begin{bmatrix}3 & 4 \\2 & 1\end{bmatrix}$,

$\mathbf{x} = \begin{bmatrix}x \\y\end{bmatrix}$,

$\mathbf{b} = \begin{bmatrix}10 \\5\end{bmatrix}$

$\mathbf{x} = A^{-1} \mathbf{b}$

In [34]:
# 계수 행렬 A와 결과 벡터 b 정의
A = np.array([[3, 4], [2, 1]])
b = np.array([10, 5])

# 행렬 A의 역행렬 계산
A_inv = np.linalg.inv(A)

# 해 계산
x = np.dot(A_inv, b)

print("Coefficient Matrix A =\n", A)
print("Result Vector b =\n", b)
print("Inverse of Coefficient Matrix A =\n", A_inv)
print("Solution Vector x =\n", x)

Coefficient Matrix A =
 [[3 4]
 [2 1]]
Result Vector b =
 [10  5]
Inverse of Coefficient Matrix A =
 [[-0.2  0.8]
 [ 0.4 -0.6]]
Solution Vector x =
 [2. 1.]


In [ ]:
a = np.array([[3, 4], [2, 1]])
b = np.array([10, 5])
a_inv = np.linalg.inv(a)
x = np.dot(a_inv, b)
print(x)

[2. 1.]


Task8_0611. 주어진 2D 평면의 점을 특정 변환 행렬을 사용하여 변환한 후, 변환된 좌표를 원래 좌표로 되돌리세요.

단계
1. 원래 점의 좌표 p와 변환 행렬 T를 정의.
2. 변환 행렬 T를 사용하여 새로운 좌표 p`를 계산.
3. 변환 행렬 T의 역행렬을 사용하여 새로운 좌표 p`에서 원래 좌표 p를 복원.

In [38]:
# 원래 점의 좌표 p와 변환 행렬 T 정의
p = np.array([1, 2])
T = np.array([[2, 0], [0, 3]])

# 변환 행렬 T를 사용하여 새로운 좌표 p 계산
new_p = np.dot(T, p)

# 변환 행렬 T의 역행렬 계산
T_inv = np.linalg.inv(T)

# 변환 행렬 T의 역행렬을 사용하여 새로운 좌표 p에서 원래 좌표 p 복원
restored_p = np.dot(T_inv, new_p)

print("Original Point P =" , p)
print("Transformation Matrix T =\n", T)
print("Transformed Point P` =", new_p)
print("Inverse of Transformation Matrix T =\n", T_inv)
print("Restored Point P` =", restored_p)

Original Point P = [1 2]
Transformation Matrix T =
 [[2 0]
 [0 3]]
Transformed Point P` = [2 6]
Inverse of Transformation Matrix T =
 [[0.5        0.        ]
 [0.         0.33333333]]
Restored Point P` = [1. 2.]
