<a href="https://colab.research.google.com/github/hyojunyee/kita_2404/blob/main/m3_%EB%B6%84%EC%84%9D%20%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC/Task/Task_0611.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Task1_0611. 주어진 대각 행렬의 역행렬을 구하고, 역행렬이 맞는지 확인하세요.

In [ ]:
D = np.diag([1, 2, 3])
D_inv = np.linalg.inv(D)
np.allclose(D, D_inv)

False

Task2_0611. 임의의 상삼각 행렬을 생성하고, 그 행렬로 부터 하삼각 행렬을 구하여 출력하세요.

In [ ]:
a = np.triu(np.random.rand(3, 3))
a.T

array([[0.57546046, 0.        , 0.        ],
       [0.3151794 , 0.41970977, 0.        ],
       [0.52470208, 0.20259493, 0.11743219]])

In [ ]:
a = np.triu(np.random.rand(3, 3))
np.round(a.T,2)

array([[0.11, 0.  , 0.  ],
       [0.42, 0.42, 0.  ],
       [0.39, 0.04, 0.02]])

In [ ]:
import random as rd

a = np.triu(np.random.randint(10, size=(3, 3)))
a.T

array([[9, 0, 0],
       [3, 9, 0],
       [1, 7, 8]])

Task3_0611. 주어진 행렬의 역행렬을 구하고, 역행렬이 맞는지 확인하세요.

In [ ]:
A = np.array([[4, 7], [2, 6]])
A_inv = np.linalg.inv(A)
np.allclose(A, A_inv)

False

Task4_0611. 주어진 데이터 포인트와 모델 파라미터를 사용하여 선형 회귀 모델의 예측값을 계산하세요.

- 1단계 : 주어진 입력 데이터 포인트 X와 모델 파라미터 θ를 정의.
- 2단계 : 행렬 곱을 사용하여 예측값 y를 계산.

In [ ]:
X = np.array([1, 2, 3])
W = np.array([0.2, 0.3, 0.4])
y = np.dot(X, W)
print(y)

2.0


Task5_0611. 주어진 입력 벡터와 가중치 행렬을 사용하여 신경망의 단일 계층 출력을 계산하세요.

- 1단계: 입력 벡터 X와 가중치 행렬 W를 정의.
- 2단계: 행렬 곱을 사용하여 계층의 출력을 계산.

In [ ]:
X = np.array([0.5, 1.0, -1.5])

# 가중치 행렬 W
W = np.array([
    [0.1, 0.2, 0.3],
    [-0.4, -0.5, -0.6],
    [-0.1, -0.2, -0.3]
])

output = np.dot(X, W)

print(output)

[-0.2 -0.1  0. ]


Task6_0611. 주어진 입력 벡터에 대해 신경망의 활성화 함수(ReLU, 시그모이드)를 적용하여 출력을 계산하세요.

- 1단계: 입력 벡터 X를 정의.
- 2단계: 가중치 행렬 W와 편향 벡터 b를 정의.
- 3단계: 활성화 함수(ReLU, 시그모이드)를 적용하여 출력을 계산
활성화 함수 적용<br>
output_relu = relu(Z)<br>
output_sigmoid = sigmoid(Z)

In [ ]:
import tensorflow as tf
from tensorflow.keras.activations import relu, sigmoid

X = np.array([1, -2, 3])
W = np.array([
    [0.1, 0.2, 0.3],
    [-0.4, -0.5, -0.6],
    [-0.1, -0.2, -0.3]
])
b = np.array([0.1, 0.2, 0.3])

Z = np.dot(X, W) + b

output_relu = relu(Z)
output_sigmoid = sigmoid(Z)
print(output_relu)
print(output_sigmoid)

tf.Tensor([0.7 0.8 0.9], shape=(3,), dtype=float64)
tf.Tensor([0.66818777 0.68997448 0.7109495 ], shape=(3,), dtype=float64)


Task7_0611. 주어진 선형 방정식을 행렬 형태로 나타내고, 역행렬을 사용하여
x와 y를 구하세요.

$\begin{cases}
3x + 4y = 10 \\
2x + y = 5
\end{cases}$

단계:
1. 계수 행렬 A와 결과 벡터 b를 정의.
2. 행렬 A의 역행렬을 구한다.
3. 역행렬을 사용하여 변수 x를 구한다.

In [ ]:
a = np.array([[3, 4], [2, 1]])
b = np.array([10, 5])
a_inv = np.linalg.inv(a)
x = np.dot(a_inv, b)
print(x)

[2. 1.]


Task8_0611. 주어진 2D 평면의 점을 특정 변환 행렬을 사용하여 변환한 후, 변환된 좌표를 원래 좌표로 되돌리세요.

단계
1. 원래 점의 좌표 p와 변환 행렬 T를 정의.
2. 변환 행렬 T를 사용하여 새로운 좌표 p를 계산.
3. 변환 행렬 T의 역행렬을 사용하여 새로운 좌표 p에서 원래 좌표 p를 복원.

In [ ]:
# 원래 점의 좌표 p와 변환 행렬 T 정의
p = np.array([1, 2])
T = np.array([[2, 0], [0, 3]])

# 변환 행렬 T를 사용하여 새로운 좌표 p 계산
new_p = np.dot(T, p)

# 변환 행렬 T의 역행렬을 사용하여 새로운 좌표 p에서 원래 좌표 p 복원
original_p = np.dot(np.linalg.inv(T), new_p)

print(new_p)
print(original_p)

[2 6]
[1. 2.]
