<a href="https://colab.research.google.com/github/hyojunyee/kita_2404/blob/main/m3_%EB%B6%84%EC%84%9D%20%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC/Task%20/%EC%97%B0%EC%8A%B5%EB%AC%B8%EC%A0%9C_numpy_Q1_0610_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## Numpy Quiz1

Q1. arange(), reshape() 이용 1차원 2차원 3차원 배열 생성

In [17]:
# arange(), reshape() 이용 1차원 2차원 3차원 배열 생성
array1 = np.arange(10)
array2 = np.arange(12).reshape(2, 6)
array3 = np.arange(20).reshape(2, 5, 2)
print(array1,'\n')
print(array2,'\n')
print(array3)

[0 1 2 3 4 5 6 7 8 9] 

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] 

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


Q2. reshape(-1,-1)을 이용 1차원을 2차원, 3차원으로 2차원을 1차원 3차원으로 3차원을 1차원 2차원으로 변환

In [37]:
resarr1 = array1.reshape(2, 5)
resarr2 = array2.reshape(2, 3, 2)
resarr3 = array3.reshape(-1)
print(resarr1,'\n')
print(resarr2,'\n')
print(resarr3)

[[0 1 2 3 4]
 [5 6 7 8 9]] 

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]] 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


Q3. Q1 1차원 배열을 실수형으로 변환

In [24]:
arr1 = np.arange(10).astype(float)
print(arr1)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


Q4. Q1 1차원 배열의 dtype을 확인

In [25]:
print(arr1.dtype)

float64


Q5. 주어진 배열에서 음수 값을 모두 0으로 변경하세요.

arr = np.array([-5, -3, -1, 0, 1, 3, 5])

In [26]:
arr = np.array([-5, -3, -1, 0, 1, 3, 5])
arr[arr < 0] = 0
print(arr)

[0 0 0 0 1 3 5]


Q6. 1 ~ 100 까지 배열에서 3의 배수인 것만을 출력

In [27]:
result = np.arange(1, 101)
print(result[result % 3 == 0])

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


Q7. 1 ~ 100 까지 배열에서 5의 배수이면서 2의 배수인 것만을 출력

In [30]:
result = np.arange(1, 101)
print(result[(result % 10 == 0)])

[ 10  20  30  40  50  60  70  80  90 100]


Q8. 1 ~ 100 까지 배열에서 3의 배수이거나 5의 배수인 것만을 출력

In [32]:
result = np.arange(1, 101)
print(result[(result % 3 == 0) | (result % 5 == 0)])

[  3   5   6   9  10  12  15  18  20  21  24  25  27  30  33  35  36  39
  40  42  45  48  50  51  54  55  57  60  63  65  66  69  70  72  75  78
  80  81  84  85  87  90  93  95  96  99 100]


Q9. 101 ~ 150 사이의 정수를 랜덤하게 추출, 2행 5열 다차원 배열을 생성 후 전치하세요

In [33]:
result = np.random.randint(101, 151, size=(2, 5))
print(result)
print(result.T)

[[145 110 107 103 144]
 [129 132 146 147 118]]
[[145 129]
 [110 132]
 [107 146]
 [103 147]
 [144 118]]


Q10. 표준정규분포로 구성된 5행 5열 다차원 배열을 생성하세요.

In [34]:
arr = np.random.randn(5, 5)
print(arr)

[[-1.60739171 -0.94360132  1.64199751  0.18827765 -0.17098516]
 [ 0.55759781 -0.60433535 -1.59410228  1.58564374  0.11553912]
 [-0.56451844  0.37673149  0.3797767   1.62482081 -0.43312102]
 [-1.29447064  1.16315686 -0.81270645  0.44205438  0.83907997]
 [ 0.13492383 -0.0684372  -1.06687195  0.13604518 -0.0453675 ]]


Q11. original_array를 1차원 배열로 변환하여 출력하세요.

In [43]:
original_array = np.array([[1, 2, 3], [4, 5, 6]])
arr_1d = original_array.reshape(-1)
print(arr_1d)

[1 2 3 4 5 6]


Q12. 주어진 2차원 배열에서 첫 번째 행을 view로 생성하고, 이 view를 수정하여 원본 배열에 반영되도록 하세요.

In [48]:
original_array = np.array([[1, 2, 3], [4, 5, 6]])
view_arr = original_array[0, :]
print(view_arr, '\n')
view_arr[0] = 10
print(view_arr, '\n')
print(original_array)

[1 2 3] 

[10  2  3] 

[[10  2  3]
 [ 4  5  6]]


Q13. 주어진 3차원 배열에서 첫 번째 2차원 배열을 view로 생성하고, 이 view를 수정하여 원본 배열에 반영되도록 하세요.

In [50]:
original_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
view_arr = original_array[0, 1, :]
print(view_arr, '\n')
view_arr[0] = 100
print(view_arr, '\n')
print(original_array)

[4 5 6] 

[100   5   6] 

[[[  1   2   3]
  [100   5   6]]

 [[  7   8   9]
  [ 10  11  12]]]


Q14. 주어진 2차원 배열을 1차원 배열 view로 reshape하고, 이 view를 수정하여 원본 배열에 반영되도록 하세요.

In [51]:
original_array = np.array([[1, 2, 3], [4, 5, 6]])
view_arr = original_array.reshape(-1)
print(view_arr, '\n')
view_arr[0] = 10
print(view_arr, '\n')
print(original_array)

[1 2 3 4 5 6] 

[10  2  3  4  5  6] 

[[10  2  3]
 [ 4  5  6]]


Q15. np.ones((10,10))을 아래와 같이 출력하세요.
```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
 ```

In [74]:
arr = np.ones((10, 10))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Q16. Q. 1 ~ 100을 아래와 같이 출력하세요.

```
[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]]
 ```

In [109]:
arr = np.arange(1, 101).reshape(10, -1)
# print(arr)
newarr = arr[::2]
np.sort(newarr, axis=-1)
newarr[::2] =
print(newarr)

ValueError: could not broadcast input array from shape (5,10) into shape (3,10)

Q17. np.ones((5,5))을 아래와 같이 출력하세요.
```
[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]]
```

In [77]:
np.ones((5,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Q18. np.arange(4)을 이용해서 아래와 같이 출력하세요.
```
[[0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 2, 0, 0, 0],
 [0, 0, 3, 0, 0],
 [0, 0, 0, 4, 0]]
```

In [95]:
# newarr = np.zeros((5,5))

# for i in range(5):
#     for j in range(5):
#         if i == j:
#             newarr[i, j] = i

# print(newarr)

[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 2. 0. 0.]
 [0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 4.]]


In [102]:
newarr = np.zeros((5,5))

for i in range(5):
    for j in range(5):
        if i == j:
            newarr[i,j-1] = i

print(newarr)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


Q19. Q. np.zeros((8,8))을 이용해서 아래와 같이 출력하세요(두가지 방식:인덱싱, tile 함수)
```
[[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0]]
```

In [ ]:
# for i in range(10):
#     arr[i] = (i+1)%2
# arr

In [89]:
newarr = np.zeros((8, 8))

for i in range(8):
    for j in range(8):
        if (i + j) % 2 == 0:
            newarr[i, j] = 1

print(newarr)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


Q20. np.arange(336).reshape(6,7,8)에서 100번째 요소의 인덱스를 구하세요.

In [85]:
np.arange(336).reshape(6,7,8)
idx = np.index(100)
print(idx)

AttributeError: module 'numpy' has no attribute 'index'