<a href="https://colab.research.google.com/github/hyojunyee/kita_2404/blob/main/m3_%EB%B6%84%EC%84%9D%20%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC/Task%20/%EC%97%B0%EC%8A%B5%EB%AC%B8%EC%A0%9C_numpy_Q1_0610_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

## Numpy Quiz1

Q1. arange(), reshape() 이용 1차원 2차원 3차원 배열 생성

In [23]:
# arange(), reshape() 이용 1차원 2차원 3차원 배열 생성
array1 = np.arange(10)
array2 = np.arange(12).reshape(2, 6)
array3 = np.arange(20).reshape(2, 5, 2)
print(array1,'\n')
print(array2,'\n')
print(array3)

[0 1 2 3 4 5 6 7 8 9] 

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] 

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


Q2. reshape(-1,-1)을 이용 1차원을 2차원, 3차원으로 2차원을 1차원 3차원으로 3차원을 1차원 2차원으로 변환

In [28]:
# 1차원을 2,3차원으로
resarr12 = array1.reshape(2, 5)
resarr13 = array1.reshape(-1, 5)
# 2차원을 1,3차원으로
resarr21 = array2.reshape(-1)
resarr23 = array2.reshape(2, 3, 2)
# 3차원을 1,2차원으로
resarr31 = array3.reshape(-1)
resarr32 = array3.reshape(-1,2)

print(resarr12,'\n')
print(resarr13,'\n')
print(resarr21,'\n')
print(resarr23,'\n')
print(resarr31,'\n')
print(resarr32)

[[0 1 2 3 4]
 [5 6 7 8 9]] 

[[0 1 2 3 4]
 [5 6 7 8 9]] 

[ 0  1  2  3  4  5  6  7  8  9 10 11] 

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]] 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] 

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


Q3. Q1 1차원 배열을 실수형으로 변환

In [34]:
arrf = array1.astype(float)
print(arrf)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


Q4. Q1 1차원 배열의 dtype을 확인

In [35]:
print(arrf.dtype)

float64


Q5. 주어진 배열에서 음수 값을 모두 0으로 변경하세요.

arr = np.array([-5, -3, -1, 0, 1, 3, 5])

In [36]:
arr = np.array([-5, -3, -1, 0, 1, 3, 5])
arr[arr < 0] = 0
# np.where(arr < 0, 0, arr)
print(arr)

[0 0 0 0 1 3 5]


Q6. 1 ~ 100 까지 배열에서 3의 배수인 것만을 출력

In [38]:
arr3 = np.arange(1, 101)
print(arr3[arr3 % 3 == 0])

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


In [37]:
a1 = np.arange(100)
a2 = a1[a1 % 3 == 0]
a2

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

Q7. 1 ~ 100 까지 배열에서 5의 배수이면서 2의 배수인 것만을 출력

In [ ]:
arr10 = np.arange(1, 101)
print(arr10[(arr10 % 10 == 0)])

[ 10  20  30  40  50  60  70  80  90 100]


In [ ]:
# a1 = np.arange(100)
# a2 = a1[(a1 % 5 ==0) & (a1 % 2==0)]
# a2

Q8. 1 ~ 100 까지 배열에서 3의 배수이거나 5의 배수인 것만을 출력

In [40]:
arr35 = np.arange(1, 101)
print(arr35[(arr35 % 3 == 0) | (arr35 % 5 == 0)])

[  3   5   6   9  10  12  15  18  20  21  24  25  27  30  33  35  36  39
  40  42  45  48  50  51  54  55  57  60  63  65  66  69  70  72  75  78
  80  81  84  85  87  90  93  95  96  99 100]


In [39]:
# a1 = np.arange(100)
# a2 = a1[(a1 % 3 ==0) | (a1 % 5==0)]
# a2

array([ 0,  3,  5,  6,  9, 10, 12, 15, 18, 20, 21, 24, 25, 27, 30, 33, 35,
       36, 39, 40, 42, 45, 48, 50, 51, 54, 55, 57, 60, 63, 65, 66, 69, 70,
       72, 75, 78, 80, 81, 84, 85, 87, 90, 93, 95, 96, 99])

Q9. 101 ~ 150 사이의 정수를 랜덤하게 추출, 2행 5열 다차원 배열을 생성 후 전치하세요

In [42]:
arrt = np.random.randint(101, 151, size=(2, 5))
# print(arrt,'\n')
print(arrt.T)
# print(np.transpose(arrt))

[[140 127]
 [143 150]
 [108 113]
 [135 127]
 [103 126]]


Q10. 표준정규분포로 구성된 5행 5열 다차원 배열을 생성하세요.

In [ ]:
arr = np.random.randn(5, 5)
print(arr)

[[-1.60739171 -0.94360132  1.64199751  0.18827765 -0.17098516]
 [ 0.55759781 -0.60433535 -1.59410228  1.58564374  0.11553912]
 [-0.56451844  0.37673149  0.3797767   1.62482081 -0.43312102]
 [-1.29447064  1.16315686 -0.81270645  0.44205438  0.83907997]
 [ 0.13492383 -0.0684372  -1.06687195  0.13604518 -0.0453675 ]]


Q11. original_array를 1차원 배열로 변환하여 출력하세요.

In [46]:
original_array = np.array([[1, 2, 3], [4, 5, 6]])
# print(original_array, '\n')

arr_1d = original_array.reshape(-1)
# flat_arr = original_array.flatten()

print(arr_1d)
# print(flat_arr)

[1 2 3 4 5 6]


Q12. 주어진 2차원 배열에서 첫 번째 행을 view로 생성하고, 이 view를 수정하여 원본 배열에 반영되도록 하세요.

In [ ]:
original_array = np.array([[1, 2, 3], [4, 5, 6]])

# 첫번째 행 view 생성
view_arr = original_array[0, :]
print(view_arr, '\n')

# view를 수정
view_arr[0] = 10

print(view_arr, '\n')
print(original_array)

[1 2 3] 

[10  2  3] 

[[10  2  3]
 [ 4  5  6]]


In [47]:
# # 2차원 배열 생성
# original_array = np.array([[1, 2, 3], [4, 5, 6]])

# # 첫 번째 행을 view로 생성
# row_view = original_array[0, :]

# # view를 수정
# row_view[0] = 10

# # 결과 확인
# print("Original Array:")
# print(original_array)
# print("Row View:")
# print(row_view)

Original Array:
[[10  2  3]
 [ 4  5  6]]
Row View:
[10  2  3]


Q13. 주어진 3차원 배열에서 첫 번째 2차원 배열을 view로 생성하고, 이 view를 수정하여 원본 배열에 반영되도록 하세요.

In [6]:
original_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# 첫번째 2차원 배열을 view로 생성
view_arr = original_array[0, 1, :]
print(view_arr, '\n')

# view를 수정
view_arr[0] = 100

print(view_arr, '\n')
print(original_array)

[4 5 6] 

[100   5   6] 

[[[  1   2   3]
  [100   5   6]]

 [[  7   8   9]
  [ 10  11  12]]]


In [48]:
# # 3차원 배열 생성
# original_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# # 첫 번째 2차원 배열을 view로 생성
# slice_view = original_array[0, :, :]

# # view를 수정
# slice_view[0, 0] = 20

# print("Original Array:")
# print(original_array)
# print("Slice View:")
# print(slice_view)

Original Array:
[[[20  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Slice View:
[[20  2  3]
 [ 4  5  6]]


Q14. 주어진 2차원 배열을 1차원 배열 view로 reshape하고, 이 view를 수정하여 원본 배열에 반영되도록 하세요.

In [7]:
original_array = np.array([[1, 2, 3], [4, 5, 6]])

# 2차원 배열을 1차원 배열로 만듬.
view_arr = original_array.reshape(-1)
print(view_arr, '\n')

# view를 수정
view_arr[0] = 10

print(view_arr, '\n')
print(original_array)

[1 2 3 4 5 6] 

[10  2  3  4  5  6] 

[[10  2  3]
 [ 4  5  6]]


In [49]:
# # 2차원 배열 생성
# original_array = np.array([[1, 2, 3], [4, 5, 6]])

# # 1차원 배열 view로 reshape
# reshaped_view = original_array.reshape(-1)

# # view를 수정
# reshaped_view[0] = 100

# # 결과 확인
# print("Original Array:")
# print(original_array)
# print("Reshaped View:")
# print(reshaped_view)

Original Array:
[[100   2   3]
 [  4   5   6]]
Reshaped View:
[100   2   3   4   5   6]


Q15. np.ones((10,10))을 아래와 같이 출력하세요.
```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
 ```

In [ ]:
arr = np.ones((10, 10))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [53]:
# arr = np.zeros((10, 10))
# arr[0:1, :] = 1
# arr[-1:, :] = 1
# arr[:, 0:1] = 1
# arr[:, -1:] = 1
# print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Q16. Q. 1 ~ 100을 아래와 같이 출력하세요.

```
[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]]
 ```

In [55]:
arr = np.arange(1, 101).reshape(10, -1)
# print(arr)
ar = []
for i in range(10):
    if i % 2 == 1:
        arr[i] = arr[i][::-1]
        ar.append(arr[i])
    # else:
    #     idx[i] = idx[i]
    #     ara.append(idx[i])
print(arr)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]]


Q17. np.ones((5,5))을 아래와 같이 출력하세요.
```
[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]]
```

In [13]:
# 5x5 크기의 배열에 0으로 채워진 2칸 두께의 패딩을 적용하여 9x9 크기의 배열을 생성
z = np.ones((5,5))
np.pad(z, pad_width=2, mode='constant', constant_values=0)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Q18. np.arange(4)을 이용해서 아래와 같이 출력하세요.
```
[[0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 2, 0, 0, 0],
 [0, 0, 3, 0, 0],
 [0, 0, 0, 4, 0]]
```

In [ ]:
# newarr = np.zeros((5,5))

# for i in range(5):
#     for j in range(5):
#         if i == j:
#             newarr[i, j] = i

# print(newarr)

[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 2. 0. 0.]
 [0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 4.]]


In [ ]:
newarr = np.zeros((5,5))

for i in range(5):
    for j in range(5):
        if i == j:
            newarr[i,j-1] = i

print(newarr)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [14]:
# np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

Q19. Q. np.zeros((8,8))을 이용해서 아래와 같이 출력하세요(두가지 방식:인덱싱, tile 함수)
```
[[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0]]
```

In [ ]:
# for i in range(10):
#     arr[i] = (i+1)%2
# arr

In [60]:
newarr = np.zeros((8, 8))

for i in range(8):
    for j in range(8):
        if (i + j) % 2 == 1:
            newarr[i, j] = 1

print(newarr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [16]:
# newarr = np.zeros((8, 8))
# newarr[1::2,::2] = 1
# newarr[::2,1::2] = 1
# print(newarr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Q20. np.arange(336).reshape(6,7,8)에서 100번째 요소의 인덱스를 구하세요.

In [58]:
arr = np.arange(336).reshape(6,7,8)
# print(arr,'\n')
index_100 = np.unravel_index(100, arr.shape)
print(index_100)

(1, 5, 4)
