<a href="https://colab.research.google.com/github/hyojunyee/kita_2404/blob/main/m6_%EB%94%A5%EB%9F%AC%EB%8B%9D/Task/Task_0827.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task1_0827. 2행 3열 텐서의 크기를 3행 2열로 변경하세요.
- view 사용
- reshape 사용
- transpose 사용

In [ ]:
# view 사용
import torch

x = torch.rand(2, 3)
print(x)
print(x.view(3, 2))

tensor([[0.2104, 0.8869, 0.1312],
        [0.0916, 0.4312, 0.6461]])
tensor([[0.2104, 0.8869],
        [0.1312, 0.0916],
        [0.4312, 0.6461]])


In [ ]:
# reshape 사용
import torch

x = torch.rand(2, 3)
print(x)
print(x.reshape(3, 2))

tensor([[0.7875, 0.0552, 0.5317],
        [0.7410, 0.7131, 0.7598]])
tensor([[0.7875, 0.0552],
        [0.5317, 0.7410],
        [0.7131, 0.7598]])


In [ ]:
# transpose 사용
import torch

x = torch.rand(2, 3)
print(x)
print(x.transpose(0, 1))

tensor([[0.7409, 0.6435, 0.0391],
        [0.6212, 0.4928, 0.8725]])
tensor([[0.7409, 0.6212],
        [0.6435, 0.4928],
        [0.0391, 0.8725]])
